### ISSUE TITLE
Test environment alternatives and tracing cookie usage

### ISSUE THREAD

**Issue by dhp-mcl** [the-markup/blacklight-query#16]
Currently when blacklight runs it uses an emulator with a fresh instance which means no cookies will be available in any of the requests. I understand there is a flag to prevent it from clearing the cache prior to executing.

Is there any way to change the environment Blacklight runs in? Can it use my local chrome installation so I can trace the usage of cookies by webpages that already exist within my normal Chrome browsing environment? If not, is there anyway to insert cookies into the emulator so that I can track their usage by various third party trackers? Thanks!

**Comment by dhp-mcl** [comment]
I tried modifying the blacklight-collector source code to set cookies and also tried used puppeteer to log into Facebook to make it automatically set its cookies. Both SEEM to work but when I observe the Facebook Pixel events, it is not picking up or using any of those cookies as I would expect them too in the emulated browser. Unsure why.

**Comment by BatMiles** [comment]
If you'd be comfortable sharing your scan results and/or your modified code, that would help me advise on this. The blacklight@themarkup.org email is probably the easiest way to do that. 

The [Blacklight Collector](https://github.com/the-markup/blacklight-collector) is set up to clear the puppeteer cache before every run by default, but this can be changed by setting the `clearCache` argument to `true`. The Collector isn't currently set up to _set_ cookies before navigating to a URL, but it looks like the [puppeteer.page.setCookie](https://github.com/puppeteer/puppeteer/blob/main/docs/api/puppeteer.page.setcookie.md) function would allow for that.

**Comment by dhp-mcl** [comment]
I am opening up the .har file from the Blacklight output in Mozilla, filtering to facebook tracking events, and viewing the cookies associated with the request. 

Typically you would see something like this in the developer tools (screenshot from Chrome, c_user is facebook profile cookie that a third party tracker is including in its event request, how/when trackers use this is of interest to me). However, when I open up the event requests from the .har file, there are no cookies (at all) associated with the request for some reason.

![unnamed](https://github.com/user-attachments/assets/38d42268-8487-4c4e-827e-0c329952be31)

**Comment by dhp-mcl** [comment]
@BatMiles I looked into the Blacklight output (requests.har) a bit closer and realized that none of the request entries have anything populated in the "cookies" field, they are all empty. For an example webpage, how is it possible that 0 cookies are included in any of the network requests (500+ requests)? (does this seem like a problem with Puppeteer or something else?

If you need an example website I tested/output to answer this, let me know and I will email.

**Comment by dhp-mcl** [comment]
After further research, it is a fault of puppeteer, the code must be customized to capture the additional request headers, otherwise, there is lots of missing information in the requests.har file.

https://stackoverflow.com/questions/47078655/missing-request-headers-in-puppeteer

**Comment by BatMiles** [comment]
@dhp-mcl , thanks for hunting that down. Since this is an issue with the puppeteer configuration, I'm going to close this issue and [open a new one](https://github.com/the-markup/blacklight-collector/issues/111) in the [blacklight-collector repo](https://github.com/the-markup/blacklight-collector).
